sonar.projectKey=uk.gov.companieshouse:elasticsearch-data-loader
sonar.projectName=elasticsearch-data-loader
sonar.host.url=${env.CODE_ANALYSIS_HOST_URL}
sonar.token=${env.CODE_ANALYSIS_TOKEN}

sonar.sources=.
sonar.exclusions=**/*_test.go,**/mock_*.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
