// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/companieshouse/elasticsearch-data-loader/write (interfaces: Writer)

// Package write is a generated GoMock package.
package write

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWriter) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWriter)(nil).Close))
}

// LogAlphaKeyErrors mocks base method.
func (m *MockWriter) LogAlphaKeyErrors(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogAlphaKeyErrors", arg0)
}

// LogAlphaKeyErrors indicates an expected call of LogAlphaKeyErrors.
func (mr *MockWriterMockRecorder) LogAlphaKeyErrors(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAlphaKeyErrors", reflect.TypeOf((*MockWriter)(nil).LogAlphaKeyErrors), arg0)
}

// LogMissingCompanyData mocks base method.
func (m *MockWriter) LogMissingCompanyData(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogMissingCompanyData", arg0)
}

// LogMissingCompanyData indicates an expected call of LogMissingCompanyData.
func (mr *MockWriterMockRecorder) LogMissingCompanyData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogMissingCompanyData", reflect.TypeOf((*MockWriter)(nil).LogMissingCompanyData), arg0)
}

// LogMissingCompanyName mocks base method.
func (m *MockWriter) LogMissingCompanyName(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogMissingCompanyName", arg0)
}

// LogMissingCompanyName indicates an expected call of LogMissingCompanyName.
func (mr *MockWriterMockRecorder) LogMissingCompanyName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogMissingCompanyName", reflect.TypeOf((*MockWriter)(nil).LogMissingCompanyName), arg0)
}

// LogPostError mocks base method.
func (m *MockWriter) LogPostError(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogPostError", arg0)
}

// LogPostError indicates an expected call of LogPostError.
func (mr *MockWriterMockRecorder) LogPostError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPostError", reflect.TypeOf((*MockWriter)(nil).LogPostError), arg0)
}

// LogUnexpectedResponse mocks base method.
func (m *MockWriter) LogUnexpectedResponse(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogUnexpectedResponse", arg0)
}

// LogUnexpectedResponse indicates an expected call of LogUnexpectedResponse.
func (mr *MockWriterMockRecorder) LogUnexpectedResponse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogUnexpectedResponse", reflect.TypeOf((*MockWriter)(nil).LogUnexpectedResponse), arg0)
}
