// Code generated by MockGen. DO NOT EDIT.
// Source: ./eshttp/eshttp.go

// Package eshttp is a generated GoMock package.
package eshttp

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAlphaKeys mocks base method.
func (m *MockClient) GetAlphaKeys(companyNames []byte, alphaKeyURL string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlphaKeys", companyNames, alphaKeyURL)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlphaKeys indicates an expected call of GetAlphaKeys.
func (mr *MockClientMockRecorder) GetAlphaKeys(companyNames, alphaKeyURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlphaKeys", reflect.TypeOf((*MockClient)(nil).GetAlphaKeys), companyNames, alphaKeyURL)
}

// SubmitBulkToES mocks base method.
func (m *MockClient) SubmitBulkToES(bulk, companyNumbers []byte, esDestURL, esDestIndex string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBulkToES", bulk, companyNumbers, esDestURL, esDestIndex)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitBulkToES indicates an expected call of SubmitBulkToES.
func (mr *MockClientMockRecorder) SubmitBulkToES(bulk, companyNumbers, esDestURL, esDestIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBulkToES", reflect.TypeOf((*MockClient)(nil).SubmitBulkToES), bulk, companyNumbers, esDestURL, esDestIndex)
}
